# Generated by Django 3.2.5 on 2021-07-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0.0)),
                ('discount', models.FloatField(default=0.0)),
                ('location', models.CharField(choices=[('Dhanmondi', 'Dhanmondi'), ('Uttara', 'Uttara'), ('Banani', 'Banani'), ('Mohammadpur', 'Mohammadpur')], max_length=100)),
                ('warranty', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=20)),
                ('refund', models.BooleanField(default=False)),
                ('exchange', models.BooleanField(default=False)),
                ('free_delivery', models.BooleanField(default=False)),
                ('free_service', models.BooleanField(default=False)),
            ],
        ),
    ]
